apiVersion: v1
kind: Namespace
metadata:
  name: devops-starter
  labels:
    # Tells Istio to automatically inject its sidecar proxy into every
    # pod created in this namespace.
    istio-injection: enabled
