# Full question bank: 4 roles x 3 levels, ~4 questions each (~48 total).
# Each question has: id, category, difficulty, question_text, hints, ideal_answer.

QUESTION_BANK = {
    "Frontend": {
        "Junior": [
            {"id":"fe-j1","category":"JavaScript","difficulty":"Junior","question_text":"What's the difference between let, const, and var?","hints":"Scoping, hoisting, reassignment","ideal_answer":"var is function-scoped and hoisted with undefined; let/const are block-scoped and live in a temporal dead zone until initialized; const forbids reassignment (but not mutation of objects)."},
            {"id":"fe-j2","category":"CSS","difficulty":"Junior","question_text":"Explain the CSS box model.","hints":"content, padding, border, margin, box-sizing","ideal_answer":"Every element is a box made of content, padding, border, and margin. box-sizing: border-box includes padding/border in the declared width, vs content-box which adds them on top."},
            {"id":"fe-j3","category":"React","difficulty":"Junior","question_text":"What is the difference between props and state in React?","hints":"Ownership, mutability, re-render triggers","ideal_answer":"Props are read-only data passed from a parent component; state is local, mutable data owned by the component that triggers a re-render when updated via setState/useState."},
            {"id":"fe-j4","category":"Web Basics","difficulty":"Junior","question_text":"What happens when you type a URL into the browser and hit enter?","hints":"DNS, TCP/TLS handshake, HTTP request, rendering","ideal_answer":"DNS resolves the domain to an IP, a TCP connection (with TLS handshake for HTTPS) is established, the browser sends an HTTP request, the server responds, and the browser parses HTML/CSS/JS to render the page."},
        ],
        "Mid": [
            {"id":"fe-m1","category":"React","difficulty":"Mid","question_text":"Explain how React reconciliation works and why keys are important in lists.","hints":"Virtual DOM, diffing algorithm","ideal_answer":"React diffs the new virtual DOM tree against the previous one using a heuristic O(n) algorithm. Keys let React match list items across renders by identity instead of position, avoiding unnecessary unmount/remount and preserving state."},
            {"id":"fe-m2","category":"Performance","difficulty":"Mid","question_text":"How would you diagnose and fix a slow-rendering React list of 5,000 items?","hints":"Virtualization, memoization, windowing","ideal_answer":"Profile with React DevTools first. Then apply windowing/virtualization (react-window), memoize expensive children with React.memo/useMemo, avoid inline object/function props causing re-renders, and paginate or lazy-load data."},
            {"id":"fe-m3","category":"CSS","difficulty":"Mid","question_text":"Compare CSS Grid and Flexbox — when would you use each?","hints":"1D vs 2D layout","ideal_answer":"Flexbox is one-dimensional (row or column) and great for distributing space along a single axis, like nav bars. Grid is two-dimensional and better for whole-page or card layouts needing both row and column control."},
            {"id":"fe-m4","category":"State Management","difficulty":"Mid","question_text":"When would you reach for Context API vs a state management library like Redux/Zustand?","hints":"Update frequency, prop drilling, devtools/middleware","ideal_answer":"Context is fine for low-frequency, low-fanout global state (theme, auth user) since every consumer re-renders on change. Redux/Zustand suit high-frequency updates, complex derived state, or when you need middleware/devtools/time-travel debugging."},
        ],
        "Senior": [
            {"id":"fe-s1","category":"Architecture","difficulty":"Senior","question_text":"How would you architect a micro-frontend setup for a large org with multiple teams?","hints":"Module federation, shared deps, versioning, deployment isolation","ideal_answer":"Use Webpack Module Federation or similar to let teams ship independently deployable bundles that share a runtime. Define contracts for shared design system/deps, version carefully to avoid duplication, and isolate failures so one micro-frontend's crash doesn't take down the shell."},
            {"id":"fe-s2","category":"Performance","difficulty":"Senior","question_text":"Walk through how you'd get a content-heavy site's Largest Contentful Paint under 2.5s.","hints":"Critical CSS, image optimization, code splitting, CDN, SSR/streaming","ideal_answer":"Measure with real-user metrics first. Then: server-render or statically generate above-the-fold content, inline critical CSS, defer non-critical JS, optimize/compress images with modern formats and proper sizing, use a CDN with edge caching, and code-split by route."},
            {"id":"fe-s3","category":"Accessibility","difficulty":"Senior","question_text":"How do you build accessibility into a component library from the start, not bolt it on later?","hints":"ARIA, keyboard nav, focus management, automated + manual testing","ideal_answer":"Bake semantic HTML and ARIA roles into base components, enforce keyboard navigation and visible focus states, manage focus on route/modal changes, run automated audits (axe) in CI, and pair with manual screen-reader testing before release."},
            {"id":"fe-s4","category":"System Design","difficulty":"Senior","question_text":"Design the frontend architecture for a real-time collaborative editor like Google Docs.","hints":"CRDTs/OT, websockets, optimistic updates, conflict resolution","ideal_answer":"Use CRDTs or operational transforms for conflict-free merging, a websocket connection for low-latency sync, optimistic local updates with server reconciliation, and presence indicators. Persist snapshots periodically to avoid replaying the full op log."},
        ],
    },
    "Backend": {
        "Junior": [
            {"id":"be-j1","category":"HTTP","difficulty":"Junior","question_text":"What's the difference between PUT and PATCH?","hints":"Full replace vs partial update, idempotency","ideal_answer":"PUT replaces the entire resource and is idempotent; PATCH applies a partial update and may or may not be idempotent depending on the operation."},
            {"id":"be-j2","category":"Databases","difficulty":"Junior","question_text":"What is a database index and why does it speed up queries?","hints":"B-trees, tradeoffs on writes","ideal_answer":"An index is a separate data structure (often a B-tree) that lets the database find rows without scanning the whole table. It speeds up reads on indexed columns but adds overhead on writes since the index must be updated too."},
            {"id":"be-j3","category":"APIs","difficulty":"Junior","question_text":"What status codes would you return for: resource created, not found, and validation error?","hints":"201, 404, 400/422","ideal_answer":"201 Created for a new resource, 404 Not Found when the resource doesn't exist, and 400 Bad Request or 422 Unprocessable Entity for validation errors."},
            {"id":"be-j4","category":"Auth","difficulty":"Junior","question_text":"Explain the difference between authentication and authorization.","hints":"Who you are vs what you can do","ideal_answer":"Authentication verifies identity (who you are, e.g. login). Authorization determines what an authenticated identity is allowed to do (permissions/roles)."},
        ],
        "Mid": [
            {"id":"be-m1","category":"Node.js","difficulty":"Mid","question_text":"How would you handle 10k concurrent requests in Node.js? Explain event loop, clustering, and backpressure.","hints":"Event loop, worker_threads, cluster","ideal_answer":"Node runs a single-threaded event loop with non-blocking I/O, so most concurrent I/O-bound requests are fine as-is. For CPU-bound work, offload to worker_threads or a job queue. Use the cluster module or a process manager to run multiple instances across cores, and apply backpressure (e.g. pausing streams, queueing) so slow consumers don't overwhelm memory."},
            {"id":"be-m2","category":"System Design","difficulty":"Mid","question_text":"Design a rate limiter for an API — how would you implement sliding window log vs token bucket in Redis?","hints":"Redis, Lua scripts, atomicity","ideal_answer":"Token bucket: each key has a token count refilled at a fixed rate, decremented per request, implemented atomically with a Redis Lua script. Sliding window log: store request timestamps in a sorted set, trim entries outside the window, and count remaining entries — more accurate but more memory-heavy than token bucket."},
            {"id":"be-m3","category":"Databases","difficulty":"Mid","question_text":"When would you choose pgvector over a dedicated vector DB like ChromaDB for RAG?","hints":"Transactional consistency, ops overhead, scale, filtering","ideal_answer":"pgvector fits when you already run Postgres and want vector search alongside relational data in one transactional store, simplifying ops and enabling SQL joins/filters. A dedicated vector DB tends to win at very large scale or when you need specialized ANN indexes and don't need relational features."},
            {"id":"be-m4","category":"Concurrency","difficulty":"Mid","question_text":"Explain optimistic vs pessimistic locking and when you'd use each.","hints":"Version columns, SELECT FOR UPDATE, contention","ideal_answer":"Pessimistic locking holds a lock (e.g. SELECT FOR UPDATE) for the duration of a transaction, blocking others — good under high contention. Optimistic locking checks a version/timestamp at commit time and retries on conflict — better when conflicts are rare and you want higher throughput."},
        ],
        "Senior": [
            {"id":"be-s1","category":"System Design","difficulty":"Senior","question_text":"Design a URL shortener that handles 100M writes/day with 99.99% availability.","hints":"ID generation, sharding, caching, read replicas","ideal_answer":"Use a distributed ID generator (Snowflake-style or pre-allocated ID ranges) to avoid write hotspots, shard the datastore by ID range or hash, cache hot redirects at the edge/CDN, and run multi-region read replicas with async replication for availability, accepting eventual consistency."},
            {"id":"be-s2","category":"Distributed Systems","difficulty":"Senior","question_text":"How do you ensure exactly-once processing in an event-driven system where consumers can crash mid-processing?","hints":"Idempotency keys, outbox pattern, at-least-once + dedup","ideal_answer":"True exactly-once delivery is hard; instead build for at-least-once delivery plus idempotent consumers (dedup via idempotency keys or a processed-events table). Use the transactional outbox pattern to atomically write state changes and events together, avoiding dual-write inconsistency."},
            {"id":"be-s3","category":"Reliability","difficulty":"Senior","question_text":"A downstream payment service has a 2% failure rate under load. How do you protect your system?","hints":"Circuit breaker, retries with backoff, bulkhead, timeouts","ideal_answer":"Set aggressive timeouts, retry with exponential backoff and jitter only for idempotent calls, wrap the dependency in a circuit breaker to fail fast once error rates spike, and use bulkheads (separate thread/connection pools) so a slow downstream doesn't exhaust resources needed by unrelated requests."},
            {"id":"be-s4","category":"Database Scaling","difficulty":"Senior","question_text":"Your Postgres primary is CPU-bound at 200k QPS. Walk through your scaling options in order.","hints":"Query/index tuning, caching, read replicas, sharding as last resort","ideal_answer":"First profile and fix slow queries/missing indexes — usually the biggest win. Add a cache (Redis) in front of hot reads. Add read replicas for read-heavy load. Only after exhausting those, consider sharding/partitioning, which adds significant operational and query complexity."},
        ],
    },
    "AI Engineer": {
        "Junior": [
            {"id":"ai-j1","category":"LLM Basics","difficulty":"Junior","question_text":"What is a token in the context of LLMs, and why does it matter for cost and context length?","hints":"Subword units, tokenizer, context window","ideal_answer":"A token is a subword unit produced by the model's tokenizer (not exactly a word). Both API cost and the model's context window are measured in tokens, so longer or less-common text can use more tokens than its word count suggests."},
            {"id":"ai-j2","category":"RAG Basics","difficulty":"Junior","question_text":"What is RAG and why use it instead of just fine-tuning?","hints":"Retrieval-augmented generation, freshness, cost","ideal_answer":"RAG retrieves relevant documents at query time and feeds them into the prompt, letting the model answer from up-to-date or private data without retraining. Fine-tuning bakes knowledge into weights, which is more expensive to update and doesn't cite sources as naturally."},
            {"id":"ai-j3","category":"Prompting","difficulty":"Junior","question_text":"What's the difference between zero-shot, few-shot, and chain-of-thought prompting?","hints":"Examples in prompt, reasoning steps","ideal_answer":"Zero-shot gives the task with no examples. Few-shot includes a handful of example input/output pairs to steer format and style. Chain-of-thought asks the model to reason step by step before answering, often improving accuracy on multi-step problems."},
            {"id":"ai-j4","category":"Embeddings","difficulty":"Junior","question_text":"What is a vector embedding and how is similarity between two embeddings measured?","hints":"Cosine similarity, dot product","ideal_answer":"An embedding is a dense numeric vector representing the semantic meaning of text (or other data). Similarity is typically measured with cosine similarity (or dot product for normalized vectors) — closer vectors mean more semantically similar content."},
        ],
        "Mid": [
            {"id":"ai-m1","category":"RAG","difficulty":"Mid","question_text":"Your RAG is hallucinating — how do you evaluate and fix it? Explain Precision@k and faithfulness.","hints":"Eval set, RAGAS-style metrics, chunking, retrieval quality","ideal_answer":"Build a labeled eval set of questions with known-correct source passages. Precision@k measures how many of the top-k retrieved chunks are actually relevant; faithfulness measures whether the generated answer is supported by the retrieved context. Fix hallucinations by improving chunking/retrieval quality, adding a 'answer only from context' instruction, and rejecting low-confidence retrievals."},
            {"id":"ai-m2","category":"Retrieval","difficulty":"Mid","question_text":"Explain hybrid search: why combine BM25 with dense vector retrieval instead of using just one?","hints":"Lexical vs semantic matching, exact term matches, reciprocal rank fusion","ideal_answer":"BM25 is strong at exact keyword/lexical matches (IDs, names, rare terms) that embeddings can miss, while dense vectors capture semantic similarity that keyword search misses. Hybrid search fuses both result sets (e.g. via reciprocal rank fusion) to get the strengths of each."},
            {"id":"ai-m3","category":"Fine-tuning","difficulty":"Mid","question_text":"When would you fine-tune a model versus just improving your prompt or RAG pipeline?","hints":"Cost, data volume, latency, task specificity","ideal_answer":"Prefer prompt engineering and RAG first since they're cheaper and faster to iterate. Fine-tune when you need consistent formatting/behavior a prompt can't reliably produce, have enough high-quality labeled examples, or need lower latency by using a smaller specialized model."},
            {"id":"ai-m4","category":"Agents","difficulty":"Mid","question_text":"You're building a multi-step agent (e.g. planner → tool-caller → evaluator). How do you prevent it from looping forever or taking unsafe actions?","hints":"Max steps, tool allowlists, human-in-the-loop, state validation","ideal_answer":"Cap the number of steps/iterations, validate state transitions so the graph can't loop indefinitely, restrict tools to an explicit allowlist with typed inputs, and add human-in-the-loop confirmation for irreversible or high-stakes actions."},
        ],
        "Senior": [
            {"id":"ai-s1","category":"LLM Ops","difficulty":"Senior","question_text":"Design an evaluation and monitoring pipeline for an LLM feature in production.","hints":"Offline eval sets, online metrics, drift detection, human review sampling","ideal_answer":"Maintain a versioned offline eval set covering key scenarios and regressions, run it in CI before deploys. In production, track online metrics (latency, cost, thumbs up/down, task success proxies), sample a percentage of outputs for human review, and watch for drift in input distribution or output quality over time, with tracing (e.g. Langfuse) tying evals back to specific prompt/model versions."},
            {"id":"ai-s2","category":"Cost & Latency","difficulty":"Senior","question_text":"Your LLM feature costs 10x more than budgeted at current traffic. How do you bring cost down without gutting quality?","hints":"Model routing, caching, prompt compression, smaller models for easy cases","ideal_answer":"Add semantic caching for repeated/similar queries, route easy queries to a cheaper/smaller model and only escalate hard ones to the expensive model, trim prompt/context to what's actually needed, and batch requests where latency allows. Measure quality impact of each change against the eval set before rolling out broadly."},
            {"id":"ai-s3","category":"RAG Architecture","difficulty":"Senior","question_text":"Design a RAG system over 10M+ documents that needs sub-200ms retrieval with per-tenant data isolation.","hints":"ANN index choice, sharding by tenant, metadata filtering, caching hot queries","ideal_answer":"Use an ANN index (HNSW/IVF) sized for the corpus, shard by tenant so queries never scan other tenants' data, apply metadata filtering at the index level rather than post-filtering, and cache embeddings/results for hot queries. Keep re-embedding pipelines incremental so index updates don't require full rebuilds."},
            {"id":"ai-s4","category":"Safety","difficulty":"Senior","question_text":"How would you guard an LLM-powered customer support agent against prompt injection from retrieved documents or user input?","hints":"Instruction/data separation, output validation, allowlisted actions","ideal_answer":"Treat retrieved/user content strictly as data, never as instructions — use structured prompts that clearly separate system instructions from untrusted content. Validate/constrain outputs before they trigger actions (e.g. schema validation, allowlisted tool calls), and avoid letting the model's tool-use decisions be steered by text embedded in documents it retrieves."},
        ],
    },
    "Fullstack": {
        "Junior": [
            {"id":"fs-j1","category":"Web Basics","difficulty":"Junior","question_text":"Explain how a REST API request flows from a React frontend to a database and back.","hints":"fetch/axios, route handler, ORM/query, response, state update","ideal_answer":"The frontend calls an API endpoint (fetch/axios), which hits a backend route handler; the handler queries the database (directly or via an ORM), gets results, serializes them to JSON, and returns a response, which the frontend uses to update its state and re-render."},
            {"id":"fs-j2","category":"Git","difficulty":"Junior","question_text":"What's the difference between git merge and git rebase?","hints":"History shape, conflict resolution timing","ideal_answer":"Merge creates a new commit joining two branch histories, preserving the true history including divergence. Rebase replays your commits on top of another branch, producing a linear history but rewriting commit hashes."},
            {"id":"fs-j3","category":"CSS/JS","difficulty":"Junior","question_text":"What is event bubbling and how would you stop it?","hints":"Event propagation, stopPropagation","ideal_answer":"Event bubbling means an event fired on a nested element propagates up through its ancestors. Call event.stopPropagation() in a handler to prevent it from continuing to bubble."},
            {"id":"fs-j4","category":"Databases","difficulty":"Junior","question_text":"What's the difference between SQL and NoSQL databases, and when might you pick each?","hints":"Schema, relationships, scaling","ideal_answer":"SQL databases enforce a fixed schema and support relational joins/transactions, good for structured, relationship-heavy data. NoSQL databases (document, key-value, etc.) are more flexible and often easier to horizontally scale, good for unstructured or rapidly evolving data."},
        ],
        "Mid": [
            {"id":"fs-m1","category":"React","difficulty":"Mid","question_text":"Explain how React reconciliation works and why keys are important in lists.","hints":"Virtual DOM, diffing algorithm","ideal_answer":"React diffs the new virtual DOM against the previous render using a heuristic algorithm, and keys let it match list items by identity across renders rather than by position, avoiding unnecessary re-mounts and state loss."},
            {"id":"fs-m2","category":"Node.js","difficulty":"Mid","question_text":"How would you handle 10k concurrent requests in Node.js? Explain event loop, clustering, and backpressure.","hints":"Event loop, worker_threads, cluster","ideal_answer":"Node's single-threaded event loop handles I/O-bound concurrency well natively; offload CPU-bound work to worker_threads, run multiple processes via cluster to use all cores, and apply backpressure on streams/queues to avoid unbounded memory growth under load."},
            {"id":"fs-m3","category":"System Design","difficulty":"Mid","question_text":"Design a rate limiter for an API — how would you implement sliding window log vs token bucket in Redis?","hints":"Redis, Lua scripts","ideal_answer":"Token bucket refills tokens at a fixed rate and decrements per request, done atomically with a Lua script. Sliding window log stores request timestamps in a sorted set and counts entries within the window — more precise but more memory-intensive."},
            {"id":"fs-m4","category":"AI","difficulty":"Mid","question_text":"Your RAG is hallucinating — how do you evaluate and fix it? Explain Precision@k and faithfulness.","hints":"RAGAS, eval set","ideal_answer":"Build an eval set of questions with known-correct sources. Precision@k measures relevance of retrieved chunks; faithfulness measures whether the answer is actually supported by them. Improve chunking and retrieval quality, and instruct the model to answer only from provided context."},
        ],
        "Senior": [
            {"id":"fs-s1","category":"System Design","difficulty":"Senior","question_text":"Design a full-stack architecture for a real-time collaborative dashboard used by 100k concurrent users.","hints":"WebSockets/SSE, horizontal scaling, pub/sub, CDN for static, DB read replicas","ideal_answer":"Use WebSockets or SSE behind a load balancer with sticky sessions or a pub/sub layer (Redis/Kafka) to fan out updates across server instances, serve static assets via CDN, scale the API horizontally behind the balancer, and use read replicas plus caching for read-heavy dashboard queries, with the DB as the source of truth for reconciliation."},
            {"id":"fs-s2","category":"Reliability","difficulty":"Senior","question_text":"Walk through your incident response when the API's p99 latency spikes 10x during a traffic surge.","hints":"Dashboards/tracing, rollback vs scale, rate limiting, postmortem","ideal_answer":"Check dashboards/tracing to isolate whether it's a specific endpoint, dependency, or resource saturation. Mitigate quickly — scale out, roll back a recent deploy, or shed load via rate limiting — before root-causing. Once stable, do a blameless postmortem and add monitoring/guardrails to catch it earlier next time."},
            {"id":"fs-s3","category":"AI Systems","difficulty":"Senior","question_text":"Design an AI feature end-to-end: a support-ticket triage assistant, from data ingestion to production monitoring.","hints":"Ingestion/embedding pipeline, retrieval, model choice, eval harness, monitoring","ideal_answer":"Ingest and chunk historical tickets, embed and index them for retrieval, build a prompt pipeline that retrieves similar past tickets plus relevant docs, choose a model size based on latency/cost/accuracy tradeoffs, validate against a labeled eval set before launch, and monitor production accuracy/cost/latency with sampled human review and drift alerts."},
            {"id":"fs-s4","category":"Security","difficulty":"Senior","question_text":"How do you secure a full-stack app against the most common web vulnerabilities (OWASP Top 10 highlights)?","hints":"Input validation, parameterized queries, auth/session hygiene, CSP, dependency scanning","ideal_answer":"Use parameterized queries/ORMs to prevent SQL injection, validate and sanitize all input, set a strong Content-Security-Policy against XSS, use secure/httpOnly cookies and short-lived tokens for session hygiene, enforce least-privilege authorization checks server-side (never trust the client), and run automated dependency vulnerability scanning in CI."},
        ],
    },
}

ROLES = list(QUESTION_BANK.keys())
LEVELS = ["Junior", "Mid", "Senior"]


def get_question_bank():
    return QUESTION_BANK


def get_bank_for(role: str, level: str):
    """Return the question list for a role/level, falling back to Fullstack/Mid
    only if the combo truly doesn't exist (kept obvious, not silent)."""
    role_bank = QUESTION_BANK.get(role)
    if role_bank and level in role_bank:
        return QUESTION_BANK[role][level]
    return QUESTION_BANK["Fullstack"]["Mid"]
