// tests/setup.ts - dummy env so unit tests don't need real credentials
process.env.UPSTASH_REDIS_REST_URL = 'https://example.upstash.io'
process.env.UPSTASH_REDIS_REST_TOKEN = 'test-token'
process.env.UPSTASH_VECTOR_REST_URL = 'https://example-vector.upstash.io'
process.env.UPSTASH_VECTOR_REST_TOKEN = 'test-token'
process.env.OPENAI_API_KEY = 'test-key'
process.env.ANTHROPIC_API_KEY = 'test-key'
process.env.LANGFUSE_SECRET_KEY = 'sk-lf-test-key-1234567890'
process.env.LANGFUSE_PUBLIC_KEY = 'pk-lf-test-key-1234567890'
process.env.LANGFUSE_HOST = 'https://cloud.langfuse.com'
process.env.GATEWAY_API_KEYS = 'test-key-123:test-tenant,other-key:tenant-2'
process.env.CACHE_CRON_SECRET = 'this-is-a-32-char-long-test-secret!!'