import {useEffect,useRef,useState} from 'react'
import {io} from 'socket.io-client'
import Visualizer from './components/Visualizer.jsx'
const API=import.meta.env.VITE_GATEWAY_URL||'http://localhost:5000'
const socket=io(API)
export default function App(){
 const [listening,setListening]=useState(false),[transcript,setTranscript]=useState(''),[partial,setPartial]=useState(''),[response,setResponse]=useState(''),[history,setHistory]=useState([]),[status,setStatus]=useState('idle'),[calendarConnected,setCalendarConnected]=useState(false),[error,setError]=useState('')
 const recorder=useRef(null),chunks=useRef([]),audio=useRef(null)
 useEffect(()=>{ const onPartial=t=>setPartial(t),onFinal=t=>{setTranscript(t);setPartial('')},onThink=()=>{setStatus('thinking');setError('')},onMemory=h=>setHistory(h),onResponse=d=>{setResponse(d.text);setHistory(h=>[...h.slice(-19),{user:d.userText,ai:d.text,tool:d.tool}]);setStatus('speaking'); if(d.audioUrl){audio.current=new Audio(d.audioUrl);audio.current.onended=()=>setStatus('idle');audio.current.onerror=()=>setStatus('idle');audio.current.play().catch(()=>setStatus('idle'))}else{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(d.text);u.onend=()=>setStatus('idle');speechSynthesis.speak(u)}}; socket.on('partial_transcript',onPartial);socket.on('final_transcript',onFinal);socket.on('ai_thinking',onThink);socket.on('memory_snapshot',onMemory);socket.on('ai_response',onResponse); fetch(`${API}/api/calendar/status`).then(r=>r.json()).then(d=>setCalendarConnected(d.connected)).catch(()=>setError('Gateway unavailable')); return()=>{socket.off('partial_transcript',onPartial);socket.off('final_transcript',onFinal);socket.off('ai_thinking',onThink);socket.off('memory_snapshot',onMemory);socket.off('ai_response',onResponse)}},[])
 const start=async()=>{if(listening)return; try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream,{mimeType:'audio/webm'});chunks.current=[];recorder.current=r;r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());setListening(false);setStatus('thinking');const buf=await new Blob(chunks.current,{type:'audio/webm'}).arrayBuffer();socket.emit('audio_chunk_final',buf)};r.start();setListening(true);setStatus('listening');socket.emit('audio_chunk_stream')}catch(e){setError('Microphone permission is required.')}}
 const stop=()=>recorder.current?.state==='recording'&&recorder.current.stop()
 const cancel=()=>{recorder.current?.stop();audio.current?.pause();audio.current=null;speechSynthesis.cancel();setListening(false);setStatus('idle')}
 const clearMemory=async()=>{await fetch(`${API}/api/memory`,{method:'DELETE'});setHistory([])}
 return <main><header><div><div className="eyebrow">LOCAL AI SYSTEM</div><h1>JARVIS <span>Lite</span></h1><p>Private voice assistant · Whisper · Ollama · Piper · Google Calendar</p></div><div className={`pill ${status}`}>● {status}</div></header>
 <section className="grid"><div className="card hero"><div className="top"><div><b>Voice console</b><small>{calendarConnected?'Calendar connected':'Calendar not connected'}</small></div><button onClick={()=>window.open(`${API}/api/calendar/auth`,'_blank')}>{calendarConnected?'Reconnect calendar':'Connect calendar'}</button></div><Visualizer active={status==='listening'}/><div className="transcript">{partial&&<span className="partial">{partial}</span>}{transcript&&<div><b>You</b>{transcript}</div>}{response&&<div><b>JARVIS</b>{response}</div>}{error&&<div className="error">{error}</div>}</div><div className="controls"><button className={`talk ${listening?'active':''}`} onMouseDown={start} onMouseUp={stop} onTouchStart={start} onTouchEnd={stop}>{listening?'Release to send':'Hold to talk'}</button><button className="secondary" onClick={cancel}>Stop</button></div><div className="hint">Tip: say “what’s on my calendar today” or use the LLM for general questions.</div></div>
 <aside className="card memory"><div className="top"><div><b>Session memory</b><small>{history.length} recent turns</small></div><button onClick={clearMemory}>Clear</button></div>{history.length===0?<div className="empty">No conversations yet.</div>:history.slice().reverse().map((h,i)=><div className="turn" key={i}><div>👤 {h.user}</div><div>🤖 {h.ai}</div>{h.tool&&<small>tool · {h.tool}</small>}</div>)}</aside></section><footer>Built with a modular React + Node.js + Python architecture. Local inference by default.</footer></main>
}
