apiVersion: v1
kind: Service
metadata:
  namespace: devops-starter
  name: postgres
spec:
  clusterIP: None   # headless - StatefulSets manage their own stable network identity
  selector:
    app: postgres
  ports:
    - port: 5432
